package com.dudhoo.nemesis.hibernate;

import com.dudhoo.nemesis.hibernate.abstracts.Entidade;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
 
public class Cidade extends Entidade implements java.io.Serializable  {

    // Fields    
     private long id;
     private Estado estado;     
     private String nome;
     private String cep;     
     private Set<Endereco> enderecos = new HashSet();


    // Constructors

    /** default constructor */
    public Cidade() {
    }

	/** minimal constructor */
    public Cidade(long id, Estado estado, Usuario usuario, String nome, String cep, Date ultMod) {
        this.id = id;
        this.estado = estado;
        this.setUsuario(usuario);
        this.nome = nome;
        this.cep = cep;
        this.setUltMod(ultMod);
    }
    
    /** full constructor */
    public Cidade(long id, Estado estado, Usuario usuario, String nome, String cep, Date ultMod, Set<Endereco> enderecos) {
        this.id = id;
        this.estado = estado;
        this.setUsuario(usuario);
        this.nome = nome;
        this.cep = cep;
        this.setUltMod(ultMod);
        this.enderecos = enderecos;
    }
    

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }
   








}
