package com.dudhoo.nemesis.hibernate;
// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.HashSet;
import java.util.Set;


/**
 * Empresa generated by hbm2java
 */

public class Empresa  implements java.io.Serializable {


    // Fields    

     private long id;
     private PessoaJuridica pessoaJuridica;
     private Imagem imagem;
     private String slogan;
     private Set<GrupoUsuario> grupoUsuarios = new HashSet();


    // Constructors

    /** default constructor */
    public Empresa() {
    }

	/** minimal constructor */
    public Empresa(long id, PessoaJuridica pessoaJuridica) {
        this.id = id;
        this.pessoaJuridica = pessoaJuridica;
    }
    
    /** full constructor */
    public Empresa(long id, PessoaJuridica pessoaJuridica, Imagem imagem, String slogan, Set<GrupoUsuario> grupoUsuarios) {
        this.id = id;
        this.pessoaJuridica = pessoaJuridica;
        this.imagem = imagem;
        this.slogan = slogan;
        this.grupoUsuarios = grupoUsuarios;
    }
    

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public PessoaJuridica getPessoaJuridica() {
        return this.pessoaJuridica;
    }
    
    public void setPessoaJuridica(PessoaJuridica pessoaJuridica) {
        this.pessoaJuridica = pessoaJuridica;
    }

    public Imagem getImagem() {
        return this.imagem;
    }
    
    public void setImagem(Imagem imagem) {
        this.imagem = imagem;
    }

    public String getSlogan() {
        return this.slogan;
    }
    
    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }

    public Set<GrupoUsuario> getGrupoUsuarios() {
        return this.grupoUsuarios;
    }
    
    public void setGrupoUsuarios(Set<GrupoUsuario> grupoUsuarios) {
        this.grupoUsuarios = grupoUsuarios;
    }
   








}
