package com.dudhoo.nemesis.hibernate;
// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Estado generated by hbm2java
 */

public class Estado  implements java.io.Serializable {


    // Fields    

     private long id;
     private Pais pais;
     private Usuario usuario;
     private String nome;
     private String sigla;
     private Date ultMod;
     private Set<Cidade> cidades = new HashSet();


    // Constructors

    /** default constructor */
    public Estado() {
    }

	/** minimal constructor */
    public Estado(long id, Pais pais, Usuario usuario, String nome, String sigla, Date ultMod) {
        this.id = id;
        this.pais = pais;
        this.usuario = usuario;
        this.nome = nome;
        this.sigla = sigla;
        this.ultMod = ultMod;
    }
    
    /** full constructor */
    public Estado(long id, Pais pais, Usuario usuario, String nome, String sigla, Date ultMod, Set<Cidade> cidades) {
        this.id = id;
        this.pais = pais;
        this.usuario = usuario;
        this.nome = nome;
        this.sigla = sigla;
        this.ultMod = ultMod;
        this.cidades = cidades;
    }
    

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public Date getUltMod() {
        return this.ultMod;
    }
    
    public void setUltMod(Date ultMod) {
        this.ultMod = ultMod;
    }

    public Set<Cidade> getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set<Cidade> cidades) {
        this.cidades = cidades;
    }
   








}
