package com.dudhoo.nemesis.hibernate;
// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Imagem generated by hbm2java
 */

public class Imagem  implements java.io.Serializable {


    // Fields    

     private BigDecimal id;
     private Usuario usuario;
     private Blob foto;
     private Date dataMod;
     private Set<Empresa> empresas = new HashSet();


    // Constructors

    /** default constructor */
    public Imagem() {
    }

	/** minimal constructor */
    public Imagem(BigDecimal id, Usuario usuario, Blob foto, Date dataMod) {
        this.id = id;
        this.usuario = usuario;
        this.foto = foto;
        this.dataMod = dataMod;
    }
    
    /** full constructor */
    public Imagem(BigDecimal id, Usuario usuario, Blob foto, Date dataMod, Set<Empresa> empresas) {
        this.id = id;
        this.usuario = usuario;
        this.foto = foto;
        this.dataMod = dataMod;
        this.empresas = empresas;
    }
    

   
    // Property accessors

    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Blob getFoto() {
        return this.foto;
    }
    
    public void setFoto(Blob foto) {
        this.foto = foto;
    }

    public Date getDataMod() {
        return this.dataMod;
    }
    
    public void setDataMod(Date dataMod) {
        this.dataMod = dataMod;
    }

    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }
   








}
