package com.dudhoo.nemesis.hibernate;
// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Observacao generated by hbm2java
 */

public class Observacao  implements java.io.Serializable {
    
    
    // Fields
    
    private long id;
    private Date ultMod;
    private String obs;
    private Set<Pessoa> pessoas = new HashSet();
    private Set<Endereco> enderecos = new HashSet();
    private Set<GrupoUsuario> grupoUsuarios = new HashSet();
    
    
    // Constructors
    
    /** default constructor */
    public Observacao() {
    }
    
    /** minimal constructor */
    public Observacao(long id, Date ultMod, String obs) {
        this.id = id;
        this.ultMod = ultMod;
        this.obs = obs;
    }
    
    /** full constructor */
    public Observacao(long id, Date ultMod, String obs, Set<Pessoa> pessoas, Set<Endereco> enderecos, Set<GrupoUsuario> grupoUsuarios) {
        this.id = id;
        this.ultMod = ultMod;
        this.obs = obs;
        this.pessoas = pessoas;
        this.enderecos = enderecos;
        this.grupoUsuarios = grupoUsuarios;
    }
    
    
    
    // Property accessors
    
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    public Date getUltMod() {
        return this.ultMod;
    }
    
    public void setUltMod(Date ultMod) {
        this.ultMod = ultMod;
    }
    
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }
    
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }
    
    public Set<GrupoUsuario> getGrupoUsuarios() {
        return this.grupoUsuarios;
    }
    
    public void setGrupoUsuarios(Set<GrupoUsuario> grupoUsuarios) {
        this.grupoUsuarios = grupoUsuarios;
    }
    
    
    
    
    
    
    
    
    
}
