package com.dudhoo.nemesis.hibernate;

import com.dudhoo.nemesis.hibernate.interfaces.Fornecedor;

// Generated 15/02/2006 22:14:25 by Hibernate Tools 3.1.0 beta1JBIDERC2


/**
 * PessoaFisica generated by hbm2java
 */
public class

PessoaFisica implements java.io.Serializable, Fornecedor{

    private long id;

    private Pessoa pessoa;

    private String nome;

    private String sobrenome;

    private String rg;

    private String telefoneResidencial;

    private Long conjugeId;

    private int estadoCivil;

    private String profissao;

    private boolean sexo;

    private String cpf;


    /** default constructor */
    public PessoaFisica(){
    }

    /** minimal constructor */
    public PessoaFisica(long idPessoaFisica, Pessoa pessoa, String nome, 
			String sobrenome, String rg, int estadoCivil, boolean sexo, String cpf){
	this.id = idPessoaFisica;
	this.pessoa = pessoa;
	this.nome = nome;
	this.sobrenome = sobrenome;
	this.rg = rg;
	this.estadoCivil = estadoCivil;
	this.sexo = sexo;
	this.cpf = cpf;
    }

    /** full constructor */
    public PessoaFisica(long idPessoaFisica, Pessoa pessoa, String nome, 
			String sobrenome, String rg, String telefoneResidencial, long conjugeId, 
			int estadoCivil, String profissao, boolean sexo, String cpf){
	this.id = idPessoaFisica;
	this.pessoa = pessoa;
	this.nome = nome;
	this.sobrenome = sobrenome;
	this.rg = rg;
	this.telefoneResidencial = telefoneResidencial;
	this.conjugeId = conjugeId;
	this.estadoCivil = estadoCivil;
	this.profissao = profissao;
	this.sexo = sexo;
	this.cpf = cpf;
    }


    // Property accessors

    public long getIdPessoaFisica(){
	return this.id;
    }

    public void setIdPessoaFisica(long idPessoaFisica){
	this.id = idPessoaFisica;
    }

    public Pessoa getPessoa(){
	return this.pessoa;
    }

    public void setPessoa(Pessoa pessoa){
	this.pessoa = pessoa;
    }

    public String getNome(){
	return this.nome;
    }

    public void setNome(String nome){
	this.nome = nome;
    }

    public String getSobrenome(){
	return this.sobrenome;
    }

    public void setSobrenome(String sobrenome){
	this.sobrenome = sobrenome;
    }

    public String getRg(){
	return this.rg;
    }

    public void setRg(String rg){
	this.rg = rg;
    }

    public String getTelefoneResidencial(){
	return this.telefoneResidencial;
    }

    public void setTelefoneResidencial(String telefoneResidencial){
	this.telefoneResidencial = telefoneResidencial;
    }

    public Long getConjugeId(){
	return this.conjugeId;
    }

    public void setConjugeId(Long conjugeId){
	this.conjugeId = conjugeId;
    }

    public String getProfissao(){
	return this.profissao;
    }

    public void setProfissao(String profissao){
	this.profissao = profissao;
    }
    
    /**
     * @return true se for masculino
     * */
    public boolean isSexo(){
	return this.sexo;
    }

    public void setSexo(boolean sexo){
	this.sexo = sexo;
    }

    public String getCpf(){
	return this.cpf;
    }

    public void setCpf(String cpf){
	this.cpf = cpf;
    }


    public void setEstadoCivil(int estadoCivil){
	this.estadoCivil = estadoCivil;
    }

    public int getEstadoCivil(){
	return estadoCivil;
    }

    public void setId(long id){
	this.id = id;
    }

    public long getId(){
	return id;
    }
    public String toString(){
	return getNome() + getSobrenome(); 
    }
}
