/*
 * JPanelEndereco.java
 *
 * Created on 15 de Fevereiro de 2006, 22:42
 */

package com.dudhoo.nemesis.swing.pessoa;

import com.dudhoo.evilframework.util.MaskUtil;
import com.dudhoo.nemesis.Application;
import com.dudhoo.nemesis.exception.ValidationException;
import com.dudhoo.nemesis.swing.JPanelObservacoes;
import com.dudhoo.nemesis.swing.StartFrame;
import com.dudhoo.nemesis.swing.cidadesRegioes.JDialogFindCidade;
import com.dudhoo.nemesis.swing.enumerations.OpcaoEscolhida;
import com.dudhoo.nemesis.hibernate.Cidade;
import com.dudhoo.nemesis.hibernate.CidadeHome;
import com.dudhoo.nemesis.hibernate.Endereco;
import javax.swing.JFormattedTextField;


/**
 *
 * @author  duduzera
 */
public class JPanelEndereco extends javax.swing.JPanel {
    private Cidade cidade;
    private Endereco endereco;
    private JPanelObservacoes obs;
    /** Creates new form JPanelEndereco */
    public JPanelEndereco() {
        jbInit();
        
        initObservacoes();
    }
    
    private void initObservacoes(){
        this.obs = new JPanelObservacoes();
        this.jTabbedPane1.add("Observações", obs);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:jbInit
    private void jbInit() {
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAndar = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        botaoProcurarCidade = new com.dudhoo.evilframework.components.BotaoProcurar16();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextCep = new JFormattedTextField(new MaskUtil().getNewMaskFormatter("#####-###"));
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldProximidade = new javax.swing.JTextField();
        botaoLimpar161 = new com.dudhoo.evilframework.components.BotaoLimpar16();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBorder(new javax.swing.border.TitledBorder("Endere\u00e7o"));
        setName("Endere\u00e7o");
        jLabel1.setText("Rua:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, -1));

        add(jTextFieldRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 330, -1));

        jLabel2.setText("Bairro:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        add(jTextFieldBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 330, -1));

        jLabel3.setText("N\u00famero:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, -1));

        add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, -1));

        jLabel4.setText("Andar:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 50, -1));

        add(jTextFieldAndar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 60, -1));

        jTextFieldCidade.setEditable(false);
        add(jTextFieldCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 300, -1));

        botaoProcurarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProcurarCidadeActionPerformed(evt);
            }
        });

        add(botaoProcurarCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 30, 20));

        jLabel7.setText("Cidade:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setText("CEP:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, -1));

        add(jFormattedTextCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, -1));

        jTabbedPane1.setName("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Complemento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, -1));

        jPanel1.add(jTextFieldComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 250, -1));

        jLabel6.setText("Proximidade:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, -1));

        jPanel1.add(jTextFieldProximidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 250, -1));

        jTabbedPane1.addTab("Inf. Compl.", null, jPanel1, "Informa\u00e7\u00f5es comlementares");

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 400, 110));

        botaoLimpar161.setToolTipText("Limpar");
        botaoLimpar161.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpar161ActionPerformed(evt);
            }
        });

        add(botaoLimpar161, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 20, 20));

    }
    // </editor-fold>//GEN-END:jbInit
    
    private void botaoLimpar161ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpar161ActionPerformed
        this.setCidade(null);
    }//GEN-LAST:event_botaoLimpar161ActionPerformed
    
    private void botaoProcurarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProcurarCidadeActionPerformed
        JDialogFindCidade cid = new JDialogFindCidade(StartFrame.getCurrentInstance(), true);
        cid.setVisible(true);
        if(cid.getOpcao() == OpcaoEscolhida.SELECT){
            CidadeHome hom = new CidadeHome();
            Cidade temp = hom.findById( cid.getIdCidade() );
            this.setCidade(temp);
            hom.closeSession();
        }
    }//GEN-LAST:event_botaoProcurarCidadeActionPerformed
    public void setCidade(Cidade cc){
        this.cidade = cc;
        if(this.cidade != null){
            this.jTextFieldCidade.setText( cidade.getNome() + " - " + cidade.getEstado().getSigla() );
            this.jFormattedTextCep.setValue(cidade.getCep() + "-000");
            this.jFormattedTextCep.requestFocus();
            this.jFormattedTextCep.setCaretPosition(6);
        }else{
            this.jTextFieldCidade.setText(null);
            this.jFormattedTextCep.setValue(null);
            this.jFormattedTextCep.setText(null);
        }
    }
    
    public Endereco getEndereco() throws ValidationException{
        if(endereco == null){
            this.endereco = new Endereco();
        }
        if(this.jTextFieldRua.getText().length() < 5){
            throw new ValidationException("Rua não pode ser nula.");
        }
        if(this.jTextFieldNumero.getText().length() < 1){ 
            throw new ValidationException("Número da residência não pode ser nulo.");
        }
        if(this.jTextFieldBairro.getText().length() < 5){
            throw new ValidationException("Bairro não pode ser nula.");
        }
        if(this.cidade == null){
            throw new ValidationException("Precisa escolher uma cidade. Não pode ser nula.");
        }
        endereco.setAndar(this.jTextFieldAndar.getText().trim());
        endereco.setBairro(this.jTextFieldBairro.getText().trim());
        endereco.setCep((this.jFormattedTextCep.getValue() != null ? this.jFormattedTextCep.getValue().toString().replace("-","") : null));
        endereco.setComplemento(this.jTextFieldComplemento.getText().trim());
        endereco.setNumero(this.jTextFieldNumero.getText().trim());
        endereco.setObservacao(obs.getObs());
        endereco.setProximidade(this.jTextFieldProximidade.getText().trim() );
        endereco.setRua(this.jTextFieldRua.getText().trim());
        endereco.setUsuario(Application.getUsuarioLogado());
        endereco.setUltMod(java.util.Calendar.getInstance().getTime());         
        if(endereco.getCep() == null || endereco.getCep().length() < 8){ 
            throw new ValidationException("Cep não pode ter menos que 8 caracteres.");
        }
        endereco.setCidade(this.cidade);
        return endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
        if(this.endereco == null){
            limpa();
        }else{
            this.jTextFieldAndar.setText(endereco.getAndar());
            this.jTextFieldBairro.setText(endereco.getBairro());                        
            this.setCidade(endereco.getCidade());
            this.jTextFieldComplemento.setText(endereco.getComplemento());
            this.jTextFieldNumero.setText(endereco.getNumero());
            this.jTextFieldProximidade.setText(endereco.getProximidade());
            this.jTextFieldRua.setText(endereco.getRua());
            obs.setObs(endereco.getObservacao());
        }
    }
    
    private void limpa(){
        String st = null;
        this.jTextFieldAndar.setText(st);
        this.jTextFieldBairro.setText(st);
        this.setCidade(null);
        this.jTextFieldComplemento.setText(st);
        this.jTextFieldNumero.setText(st);
        this.jTextFieldProximidade.setText(st);
        this.jTextFieldRua.setText(st);
        this.obs.setObs(null);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dudhoo.evilframework.components.BotaoLimpar16 botaoLimpar161;
    private com.dudhoo.evilframework.components.BotaoProcurar16 botaoProcurarCidade;
    private javax.swing.JFormattedTextField jFormattedTextCep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAndar;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldProximidade;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
    
}
