package com.dudhoo.nemesis.hibernate;
// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Endereco generated by hbm2java
 */

public class Endereco  implements java.io.Serializable {


    // Fields    

     private long id;
     private Observacao observacao;
     private Usuario usuario;
     private Cidade cidade;
     private String rua;
     private String bairro;
     private Date ultMod;
     private String cep;
     private String complemento;
     private String proximidade;
     private String numero;
     private String andar;
     private Set<Pessoa> pessoas = new HashSet();


    // Constructors

    /** default constructor */
    public Endereco() {
    }

	/** minimal constructor */
    public Endereco(long id, Usuario usuario, Cidade cidade, String rua, String bairro, Date ultMod, String cep, String numero) {
        this.id = id;
        this.usuario = usuario;
        this.cidade = cidade;
        this.rua = rua;
        this.bairro = bairro;
        this.ultMod = ultMod;
        this.cep = cep;
        this.numero = numero;
    }
    
    /** full constructor */
    public Endereco(long id, Observacao observacao, Usuario usuario, Cidade cidade, String rua, String bairro, Date ultMod, String cep, String complemento, String proximidade, String numero, String andar, Set<Pessoa> pessoas) {
        this.id = id;
        this.observacao = observacao;
        this.usuario = usuario;
        this.cidade = cidade;
        this.rua = rua;
        this.bairro = bairro;
        this.ultMod = ultMod;
        this.cep = cep;
        this.complemento = complemento;
        this.proximidade = proximidade;
        this.numero = numero;
        this.andar = andar;
        this.pessoas = pessoas;
    }
    

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public Observacao getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(Observacao observacao) {
        this.observacao = observacao;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }

    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public Date getUltMod() {
        return this.ultMod;
    }
    
    public void setUltMod(Date ultMod) {
        this.ultMod = ultMod;
    }

    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    public String getProximidade() {
        return this.proximidade;
    }
    
    public void setProximidade(String proximidade) {
        this.proximidade = proximidade;
    }

    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getAndar() {
        return this.andar;
    }
    
    public void setAndar(String andar) {
        this.andar = andar;
    }

    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }
   








}
