package com.dudhoo.nemesis.hibernate;
// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * GrupoUsuario generated by hbm2java
 */
public class

GrupoUsuario implements java.io.Serializable{


    // Fields    

    private long id;
    private Observacao observacao;
    private Empresa empresa;
    private Usuario usuario;
    private String nome;
    private String descricao;
    private Date ultMod;
    private Set<Permissoes> permissoeses = new HashSet();
    private Set<Usuario> usuarios     = new HashSet();

    // Constructors

    /** default constructor */
    public GrupoUsuario(){
    }

    public String toString(){
	return nome;
    }

    /** minimal constructor */
    public GrupoUsuario(long id, Empresa empresa, Usuario usuario, String nome, 
			Date ultMod){
	this.id = id;
	this.empresa = empresa;
	this.usuario = usuario;
	this.nome = nome;
	this.ultMod = ultMod;
    }

    /** full constructor */
    public GrupoUsuario(long id, Observacao observacao, Empresa empresa, 
			Usuario usuario, String nome, String descricao, Date ultMod, 
			Set<Permissoes> permissoeses){
	this.id = id;
	this.observacao = observacao;
	this.empresa = empresa;
	this.usuario = usuario;
	this.nome = nome;
	this.descricao = descricao;
	this.ultMod = ultMod;
	this.permissoeses = permissoeses;
    }


    // Property accessors

    public long getId(){
	return this.id;
    }

    public void setId(long id){
	this.id = id;
    }

    public Observacao getObservacao(){
	return this.observacao;
    }

    public void setObservacao(Observacao observacao){
	this.observacao = observacao;
    }

    public Empresa getEmpresa(){
	return this.empresa;
    }

    public void setEmpresa(Empresa empresa){
	this.empresa = empresa;
    }

    public Usuario getUsuario(){
	return this.usuario;
    }

    public void setUsuario(Usuario usuario){
	this.usuario = usuario;
    }

    public String getNome(){
	return this.nome;
    }

    public void setNome(String nome){
	this.nome = nome;
    }

    public String getDescricao(){
	return this.descricao;
    }

    public void setDescricao(String descricao){
	this.descricao = descricao;
    }

    public Date getUltMod(){
	return this.ultMod;
    }

    public void setUltMod(Date ultMod){
	this.ultMod = ultMod;
    }

    public Set<Permissoes> getPermissoeses(){
	return this.permissoeses;
    }

    public void setPermissoeses(Set<Permissoes> permissoeses){
	this.permissoeses = permissoeses;
    }


    public void setUsuarios(Set <Usuario> usuarios){
	this.usuarios = usuarios;
    }

    public Set <Usuario> getUsuarios(){
	return usuarios;
    }
}
