package com.dudhoo.nemesis.hibernate;
// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2



/**
 * Permissoes generated by hbm2java
 */

public class Permissoes  implements java.io.Serializable {


    // Fields    

     private long id;
     private GrupoUsuario grupoUsuario;
     private String chave;
     private String valor;


    // Constructors

    /** default constructor */
    public Permissoes() {
    }

    
    /** full constructor */
    public Permissoes(long id, GrupoUsuario grupoUsuario, String chave, String valor) {
        this.id = id;
        this.grupoUsuario = grupoUsuario;
        this.chave = chave;
        this.valor = valor;
    }
    

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public GrupoUsuario getGrupoUsuario() {
        return this.grupoUsuario;
    }
    
    public void setGrupoUsuario(GrupoUsuario grupoUsuario) {
        this.grupoUsuario = grupoUsuario;
    }

    public String getChave() {
        return this.chave;
    }
    
    public void setChave(String chave) {
        this.chave = chave;
    }

    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
   








}
