package com.dudhoo.nemesis.hibernate;
// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Ramo generated by hbm2java
 */

public class Ramo  implements java.io.Serializable {


    // Fields    

     private long id;
     private Usuario usuario;
     private String nome;
     private String descricao;
     private Date ultMod;
     private Set<Pessoa> pessoas = new HashSet();


    // Constructors

    /** default constructor */
    public Ramo() {
    }

	/** minimal constructor */
    public Ramo(long id, Usuario usuario, String nome, Date ultMod) {
        this.id = id;
        this.usuario = usuario;
        this.nome = nome;
        this.ultMod = ultMod;
    }
    
    /** full constructor */
    public Ramo(long id, Usuario usuario, String nome, String descricao, Date ultMod, Set<Pessoa> pessoas) {
        this.id = id;
        this.usuario = usuario;
        this.nome = nome;
        this.descricao = descricao;
        this.ultMod = ultMod;
        this.pessoas = pessoas;
    }
    

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Date getUltMod() {
        return this.ultMod;
    }
    
    public void setUltMod(Date ultMod) {
        this.ultMod = ultMod;
    }

    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }
   








}
