package com.dudhoo.nemesis.hibernate;

// Generated 23/01/2006 21:05:43 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */

public class Usuario  implements java.io.Serializable {

	// Fields

	private long id;

	private String username;

	private String senha;

	private Date ultMod;

	private String nome;

	private String celular;

	private String email;

	private Date expira;

	private Long imagemId;
	
	private long grupoUsuarioId;

	private Set<Cidade> cidades = new HashSet();

	private Set<Usuario> usuarios = new HashSet();

	private Set<Estado> estados = new HashSet();

	private Set<Pessoa> pessoas = new HashSet();

	private Set<Pais> paises = new HashSet();

	private Set<Endereco> enderecos = new HashSet();

	private Set<GrupoUsuario> grupoUsuarios = new HashSet();

	private Set<Ramo> ramos = new HashSet();

	private Set<Imagem> imagems = new HashSet();

	// Constructors

	/** default constructor */
	public Usuario() {
	}

	/** minimal constructor */
	public Usuario(long id, String username, String senha,
			Date ultMod, String nome) {
		this.id = id;
		
		this.username = username;
		this.senha = senha;
		this.ultMod = ultMod;
		this.nome = nome;
	}

	/** full constructor */
	public Usuario(long id, Usuario usuario, String username, String senha,
			Date ultMod, String nome, String celular, String email,
			Date expira, long imagemId, Set<Cidade> cidades,
			Set<Usuario> usuarios, Set<Estado> estados, Set<Pessoa> pessoas,
			Set<Pais> paises, Set<Endereco> enderecos,
			Set<GrupoUsuario> grupoUsuarios, Set<Ramo> ramos,
			Set<Imagem> imagems) {
		this.id = id;		
		this.username = username;
		this.senha = senha;
		this.ultMod = ultMod;
		this.nome = nome;
		this.celular = celular;
		this.email = email;
		this.expira = expira;
		this.imagemId = imagemId;
		this.cidades = cidades;
		this.usuarios = usuarios;
		this.estados = estados;
		this.pessoas = pessoas;
		this.paises = paises;
		this.enderecos = enderecos;
		this.grupoUsuarios = grupoUsuarios;
		this.ramos = ramos;
		this.imagems = imagems;
	}

	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public Date getUltMod() {
		return this.ultMod;
	}

	public void setUltMod(Date ultMod) {
		this.ultMod = ultMod;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getExpira() {
		return this.expira;
	}

	public void setExpira(Date expira) {
		this.expira = expira;
	}

	public Long getImagemId() {
		return this.imagemId;
	}

	public void setImagemId(Long imagemId) {
        	this.imagemId = imagemId;
	}

	public Set<Cidade> getCidades() {
		return this.cidades;
	}

	public void setCidades(Set<Cidade> cidades) {
		this.cidades = cidades;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public Set<Estado> getEstados() {
		return this.estados;
	}

	public void setEstados(Set<Estado> estados) {
		this.estados = estados;
	}

	public Set<Pessoa> getPessoas() {
		return this.pessoas;
	}

	public void setPessoas(Set<Pessoa> pessoas) {
		this.pessoas = pessoas;
	}

	public Set<Pais> getPaises() {
		return this.paises;
	}

	public void setPaises(Set<Pais> paises) {
		this.paises = paises;
	}

	public Set <Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

	public Set <GrupoUsuario> getGrupoUsuarios() {
		return this.grupoUsuarios;
	}

	public void setGrupoUsuarios(Set<GrupoUsuario> grupoUsuarios) {
		this.grupoUsuarios = grupoUsuarios;
	}

	public Set<Ramo> getRamos() {
		return this.ramos;
	}

	public void setRamos(Set<Ramo> ramos) {
		this.ramos = ramos;
	}

	public Set<Imagem> getImagems() {
		return this.imagems;
	}

	public void setImagems(Set<Imagem> imagems) {
		this.imagems = imagems;
	}
	
	public String toString(){
	    return this.username + " - " + this.email; 
	}

    public void setGrupoUsuarioId(long grupoUsuarioId){
	this.grupoUsuarioId = grupoUsuarioId;
    }

    public long getGrupoUsuarioId(){
	return grupoUsuarioId;
    }
}
