/*
 * JDialogGeneric.java
 *
 * Created on 8 de Fevereiro de 2006, 23:45
 */

package com.dudhoo.nemesis.swing.generic;

import com.dudhoo.evilframework.swing.EvilError;
import com.dudhoo.evilframework.swing.EvilInformation;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.LayoutManager;
import java.awt.Toolkit;

/**
 *
 * @author  duduzera
 */
abstract class JDialogGeneric extends javax.swing.JDialog {
    
    /**
     * Creates new form JDialogGeneric
     */
    public JDialogGeneric(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        jbInit();
        centralize();
        this.setAlwaysOnTop(true);
        pack();
    }
    /**Deixa centralizado*/
    public void centralize(){
        this.setLocationRelativeTo(null);
        /*Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((d.getWidth() - getWidth()) / 2);
        int y = (int) ((d.getHeight() - getHeight()) / 2);
        setLocation(x, y);*/
    }
    /**@deprecated use close() é mais bonito eheh*/
    public void fechar(){
        this.dispose();
    }
    /**Fecha-o*/
    public void close(){
	this.dispose();
    }
    /**Adiciona componente no rodapé.
     */
    public void addBotaoAtBottom(Component c){
        try{
            this.jPanelBottom.add(c);
        }catch(Exception xxx){
            new EvilError(null, false, xxx).setVisible(true);
        }
    }
    /**Adiciona um panelMovimentacaoEstoque no centro,uma vez que o centro é borderLayout
     */
    public void addPanelAtCenter(Component c){
        this.add(c, BorderLayout.CENTER);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:jbInit
    private void jbInit() {
        jPanelBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanelBottom.setBorder(new javax.swing.border.EtchedBorder());
        getContentPane().add(jPanelBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:jbInit
    
    public void erro(Frame fram,Throwable bt){
        new com.dudhoo.evilframework.swing.EvilError(fram, true, bt).setVisible(true);
    }
    /**
     * Mostra a mensagem "Salvo com sucesso!"
     * */
    public void messageAfterTheSaveWithSucess(Component comp){
        new EvilInformation(comp).showMessage("Salvo com sucesso!");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel jPanelBottom;
    // End of variables declaration//GEN-END:variables
    
}
