/*
 * JPanelObservacoes.java
 *
 * Created on 20 de Fevereiro de 2006, 22:57
 */

package com.dudhoo.nemesis.swing;

import com.dudhoo.nemesis.hibernate.Observacao;
import java.util.Observable;

/**
 *
 * @author  duduzera
 */
public class JPanelObservacoes extends javax.swing.JPanel {
    private Observacao obs;
    /** Creates new form JPanelObservacoes */
    public JPanelObservacoes() {
        jbInit();
    }

    public Observacao getObs() {        
        int t = this.jTextAreaObs.getText().trim().length();
        if(t > 0){
            if(obs == null){
                obs = new Observacao();                          
            }
            obs.setObs(this.jTextAreaObs.getText().trim());
            obs.setUltMod(java.util.Calendar.getInstance().getTime());    
        }else{
            obs = null;
        }
        return obs;
    }

    public void setObs(Observacao _obs) {        
        this.obs = _obs;
        if(_obs != null){
            refresh();
        }
    }
    public void refresh(){
        this.jTextAreaObs.setText( (this.obs == null ? null : obs.getObs() ));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:jbInit
    private void jbInit() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("Observa\u00e7\u00f5es"));
        jTextAreaObs.setFont(new java.awt.Font("Courier", 1, 13));
        jTextAreaObs.setLineWrap(true);
        jScrollPane1.setViewportView(jTextAreaObs);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:jbInit
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaObs;
    // End of variables declaration//GEN-END:variables
    
}
