/*
 * JPanelCadRamos.java
 *
 * Created on 16 de Fevereiro de 2006, 21:57
 */

package com.dudhoo.nemesis.swing.ramos;

import com.dudhoo.nemesis.exception.ValidationException;
import com.dudhoo.nemesis.hibernate.Ramo;

/**
 *
 * @author  duduzera
 */
public class JPanelCadRamos extends javax.swing.JPanel {
    private Ramo ramo = null; 
    /**
     * Creates new form JPanelCadRamos 
     */
    public JPanelCadRamos() {
        jbInit();        
    }
    
    public Ramo getRamo() throws ValidationException{
        if(ramo == null){
            ramo = new Ramo();
        }
        String nome = this.jTextFieldNome.getText().trim();
        String desc = this.jTextAreaDescricao.getText().trim();
        if(nome.length() < 1 ){
            throw new ValidationException("Informe o nome do ramo.");
        }else if(desc.length() < 1){
            throw new ValidationException("Informe a descrição do ramo.");
        }
        ramo.setNome(nome);
        ramo.setDescricao(desc);
        return ramo;
    }
    public void setRamo(Ramo _ramo){
        this.ramo = _ramo;
        if(ramo != null){
            this.jTextAreaDescricao.setText(ramo.getDescricao());
            this.jTextFieldNome.setText(ramo.getNome());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:jbInit
    private void jbInit() {
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBorder(new javax.swing.border.TitledBorder("Ramo:"));
        add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 240, -1));

        jLabel1.setText("Nome:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setText("Descri\u00e7\u00e3o:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jScrollPane1.setViewportView(jTextAreaDescricao);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 240, 90));

    }
    // </editor-fold>//GEN-END:jbInit
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
    
}
