/*
 * JPanelCidade.java
 *
 * Created on 14 de Fevereiro de 2006, 23:48
 */

package com.dudhoo.nemesis.swing.cidadesRegioes;

import com.dudhoo.evilframework.util.MaskUtil;
import com.dudhoo.nemesis.exception.ValidationException;
import com.dudhoo.nemesis.hibernate.Cidade;
import javax.swing.JFormattedTextField;

/**
 *
 * @author  duduzera
 */
public class JPanelCidade extends javax.swing.JPanel {
    private Cidade cidade;
    /** Creates new form JPanelCidade */
    public JPanelCidade() {
        jbInit();        
    }

    public Cidade getCidade() throws ValidationException{
        if(cidade == null){
            cidade = new Cidade();
        }
        if(this.jFormattedCep.getValue() == null){
            throw new ValidationException("Insira o CEP da Cidade.");
        }
        int citiMin = 3;
        if(this.jTextFieldNome.getText().length() < citiMin ){
            throw new ValidationException("Digite o nome da cidade. Mais de " 
                    + citiMin + " caracteres"); //TODO VER UMA FRASE DE ERRO MELHOR
        }
        cidade.setCep(this.jFormattedCep.getValue().toString());
        cidade.setNome(this.jTextFieldNome.getText());
        return cidade;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
        if(cidade != null){
            this.jFormattedCep.setValue(cidade.getCep());
            this.jTextFieldNome.setText(cidade.getNome());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:jbInit
    private void jbInit() {
        jLabel1 = new javax.swing.JLabel();
        jFormattedCep = new JFormattedTextField(
            new MaskUtil().getNewMaskFormatter("#####"));
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBorder(new javax.swing.border.TitledBorder("Cidade"));
        jLabel1.setText("Cep:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jFormattedCep.setToolTipText("5 primeiros d\u00edgitos do CEP");
        add(jFormattedCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, -1));

        jLabel3.setText("Nome:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, -1));

    }
    // </editor-fold>//GEN-END:jbInit
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedCep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
    
}
