/*
 * EvilError.java
 *
 * Created on 25 de Janeiro de 2006, 21:22
 */

package com.dudhoo.evilframework.swing;

import org.apache.log4j.Logger;


/**
 *
 * @author  duduzera
 */
public class EvilError extends javax.swing.JDialog {
    private Logger log = Logger.getLogger(this.getClass());
    /**
     * Creates new form EvilError 
     * */
    private Throwable throwable = null;
    
    public EvilError(java.awt.Frame parent, boolean modal, Throwable e) {
        super(parent, modal);
        try {
            jbInit();
        } catch (Exception f) {            
            f.printStackTrace();
        }
        initDudu();
	this.throwable = e;
        if(e != null){
            for(int i = 0; i < e.getStackTrace().length; i++){
                this.jTextArea1.append( e.getStackTrace()[i].toString() + "\n");
            }
            this.jLabel2.setText("<html>" + e.getMessage() + "</html>");            
            
        }       
        isNeedeToBeVisible();
    }
    public void setVisible(boolean visible){
	super.setVisible(visible);
	log.error("EvilErro mostrado ao usuário. ", throwable);
    }
    private void initDudu(){
        this.setAlwaysOnTop(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void jbInit() throws Exception {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        jLabelImutable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButtonShowDetails = new javax.swing.JToggleButton();
        duduPanelImage = new com.dudhoo.evilframework.components.DuduPanelImage();
        jPanelSouth = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Erro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelCenter.setLayout(new java.awt.GridBagLayout());

        jPanelCenter.setBorder(new javax.swing.border.EtchedBorder());
        jLabelImutable.setText("Desculpe. O seguinte erro ocorreu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        jPanelCenter.add(jLabelImutable, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Erro...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelCenter.add(jLabel2, gridBagConstraints);

        jScrollPane.setToolTipText("Detalhe do erro");
        jTextArea1.setColumns(11);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Courier", 0, 12));
        jTextArea1.setRows(6);
        jScrollPane.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        jPanelCenter.add(jScrollPane, gridBagConstraints);

        jToggleButtonShowDetails.setText("Mostrar detalhes");
        jToggleButtonShowDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShowDetailsActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.0010;
        gridBagConstraints.weighty = 0.0010;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanelCenter.add(jToggleButtonShowDetails, gridBagConstraints);

        duduPanelImage.setImage("com/dudhoo/evilframework/resources/images/Bug.png");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanelCenter.add(duduPanelImage, gridBagConstraints);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setBorder(new javax.swing.border.EtchedBorder());
        jButton1.setMnemonic('O');
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanelSouth.add(jButton1);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-415)/2, (screenSize.height-224)/2, 415, 224);
    }
    // </editor-fold>//GEN-END:initComponents
    
    private void jToggleButtonShowDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShowDetailsActionPerformed
        isNeedeToBeVisible();
        setVisible(true);
    }//GEN-LAST:event_jToggleButtonShowDetailsActionPerformed
    /**Ve se é preciso ficar visível
     */
    private void isNeedeToBeVisible(){
        this.duduPanelImage.setVisible(this.jToggleButtonShowDetails.isSelected());
        this.jScrollPane.setVisible(this.jToggleButtonShowDetails.isSelected());
        if(this.jToggleButtonShowDetails.isSelected()){
            this.jToggleButtonShowDetails.setText("Esconder detalhes");
            aumentarAltura();
        }else{
            this.jToggleButtonShowDetails.setText("Mostrar detalhes");
            diminuirTamanho();
        }        
    }
    private void aumentarAltura(){
        this.setSize((int)this.getSize().getWidth(), 320);
    }
    private void diminuirTamanho(){
        this.setSize((int)this.getSize().getWidth(), 220);
        
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fecha();
    }//GEN-LAST:event_formWindowClosing
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fecha();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void fecha(){
        this.dispose();
        if( this.getParent() != null){
            this.getParent().remove(this);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dudhoo.evilframework.components.DuduPanelImage duduPanelImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImutable;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButtonShowDetails;
    // End of variables declaration//GEN-END:variables
    
}
