/*
 * PanelAbout.java
 *
 * Created on 11 de Janeiro de 2006, 22:22
 */

package com.dudhoo.nemesis.swing;

import com.dudhoo.evilframework.components.DuduPanelImage;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author  dudu
 */
public class PanelAbout extends DuduPanelImage{
    
    /** Creates new form PanelAbout */
    public PanelAbout() {
        jbInit();        
        this.setSize(440,254);
    }
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */   
    private void jbInit() {

        setImage("com/dudhoo/nemesis/resources/about.jpg");
	this.setSize(new Dimension(400, 254));
    }
   
}
