/*
 * JPanelPais.java
 *
 * Created on 9 de Fevereiro de 2006, 20:10
 */

package com.dudhoo.nemesis.swing.cidadesRegioes;

import com.dudhoo.evilframework.swing.EvilError;
import com.dudhoo.evilframework.util.MaskUtil;
import com.dudhoo.nemesis.exception.ValidationException;
import com.dudhoo.nemesis.hibernate.Pais;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import org.apache.log4j.Logger;

/**
 *
 * @author  duduzera
 */
public class JPanelPais extends javax.swing.JPanel {
    Pais pais = null;
    /** Creates new form JPanelPais */
    public JPanelPais() {
        jbInit();
    }
    public void setPais(Pais p){
        this.pais = p;
        this.jTextFieldPais.setText(this.pais.getNome());
        this.jTextFieldSigla.setText(this.pais.getSigla());
    }
    public Pais getPais() throws ValidationException{
        if(pais == null){
            pais = new Pais();
        }
        String nome     = this.jTextFieldPais.getText().trim() ; 
        String sigla    = this.jTextFieldSigla.getText().trim().toUpperCase();
        int size = 3; //TODO TEM QUE SER ESPECIFICADO NAS CONFIGURAÇOES E SALVO NO BANCO
        int siglaSize = 2;
        
        if(nome.length() < size){
            throw new ValidationException("O nome tem que ter mais de " + (size - 1) + " caracteres");
        }else if(sigla.length() < siglaSize){
            throw new ValidationException("A sigla deve possuir no mínimo " + siglaSize + " caracteres.");
        }
        
        pais.setNome( nome );        
        pais.setSigla(sigla);
        return pais;
    }
    
    public String getNomePais(){
        return this.jTextFieldPais.getText();
    }
    
    public String getSigla(){
        return this.jTextFieldSigla.getText();
    }
    public void limpa(){
        this.jTextFieldPais.setText("");
        this.jTextFieldSigla.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:jbInit
    private void jbInit() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jTextFieldSigla = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBorder(new javax.swing.border.TitledBorder("Pa\u00eds"));
        jLabel1.setText("Pa\u00eds:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setText("Sigla:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        add(jTextFieldPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 190, -1));

        add(jTextFieldSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, -1));

    }
    // </editor-fold>//GEN-END:jbInit
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldSigla;
    // End of variables declaration//GEN-END:variables
    
}
