// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package com.dudhoo.nemesis.webservices;

public interface NWebServicePortType extends java.rmi.Remote {
    public java.util.List getAllProdutos() throws 
         java.rmi.RemoteException;
    public java.util.Date getTimestamp() throws 
         java.rmi.RemoteException;
    public void newClientePf(com.dudhoo.nemesis.hibernate.PessoaFisica pf) throws 
         java.rmi.RemoteException;
    public void newClientePj(com.dudhoo.nemesis.hibernate.PessoaJuridica pj) throws 
         java.rmi.RemoteException;
    public void newOrder(com.dudhoo.nemesis.hibernate.Produto prod, long valorUnitario, com.dudhoo.nemesis.hibernate.Pessoa cliente, long quantidade, com.dudhoo.nemesis.hibernate.Observacao obs) throws 
         java.rmi.RemoteException;
}
