/*
 * JTabbedPanelRootPessoa.java
 *
 * Created on 16 de Fevereiro de 2006, 00:08
 */

package com.dudhoo.nemesis.swing.pessoa;

import com.dudhoo.nemesis.exception.ValidationException;
import com.dudhoo.nemesis.hibernate.Endereco;
import com.dudhoo.nemesis.hibernate.Pessoa;
import com.dudhoo.nemesis.hibernate.PessoaHome;
import com.dudhoo.nemesis.hibernate.Ramo;
import org.hibernate.LockMode;

/**
 * Este panelMovimentacaoEstoque é o root. Pessoa física e jurídica derivarão desse jpanel.
 * @author duduzera
 */
public class JTabbedPanelRootPessoa extends javax.swing.JTabbedPane {
    private JPanelRamo ram ;
    private JPanelEndereco end ;
    private JPanelPessoa panelpessoa ;
    
    /** Creates new form BeanForm */
    public JTabbedPanelRootPessoa() {
        jbInit();
        initTabs();
        
    }
    private void initTabs(){
        this.panelpessoa = new JPanelPessoa();
        this.addTab("Pessoa", this.panelpessoa);        
        this.end = new JPanelEndereco();
        this.addTab("Endereço", this.end);
        this.ram = new JPanelRamo();
        this.addTab("Ramo", ram);       
    }
    
    public Ramo getRamo() throws ValidationException{
        return ram.getRamo();
    }
    
    public Endereco getEndereco() throws ValidationException{
        return end.getEndereco();
    }
    public void setRamo(Ramo ramo){
        this.ram.setRamo(ramo);
    }
    
    public Pessoa getPessoa() throws Exception, NullPointerException{
        Pessoa p = this.panelpessoa.getPessoa();    
        p.setRamo(getRamo());        
        p.setEndereco(getEndereco());
        return p;
    }
    
    protected void setPessoa(Pessoa pes){
        panelpessoa.setPessoa(pes);
        end.setEndereco(pes.getEndereco());
        ram.setRamo(pes.getRamo());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:jbInit
    private void jbInit() {

    }
    // </editor-fold>//GEN-END:jbInit
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
