/*
 * BotaoEditar16.java
 *
 * Created on 8 de Fevereiro de 2006, 20:52
 */

package com.dudhoo.evilframework.components;

/**
 *
 * @author  duduzera
 */
public class BotaoEditar16 extends javax.swing.JButton {

    /** Creates new form BeanForm */
    public BotaoEditar16() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        setIcon(new javax.swing.ImageIcon(getClass()
                                          .getResource("/com/dudhoo/evilframework/resources/images/Edit16.gif")));
        setToolTipText("Editar");
    }
}
