/*
 * BotaoFechar24.java
 *
 * Created on 8 de Fevereiro de 2006, 22:07
 */

package com.dudhoo.evilframework.components;

/**
 *
 * @author  duduzera
 */
public class BotaoFechar24 extends javax.swing.JButton {
    
    /** Creates new form BeanForm */
    public BotaoFechar24() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dudhoo/evilframework/resources/images/stock_close_24.png")));
        setText("Fechar");
        setToolTipText("Fechar");
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
