/*
 * BotaoLimpar16.java
 *
 * Created on 18 de Fevereiro de 2006, 17:14
 */

package com.dudhoo.evilframework.components;

/**
 *
 * @author  duduzera
 */
public class BotaoLimpar16 extends javax.swing.JButton {
    
    /** Creates new form BeanForm */
    public BotaoLimpar16() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dudhoo/evilframework/resources/images/stock_clear_16.png")));
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
