/*
 * DuduPanelImage.java
 *
 * Created on 11 de Janeiro de 2006, 23:13
 */

package com.dudhoo.evilframework.components;

import java.awt.Graphics;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author  dudu
 */
public class DuduPanelImage extends javax.swing.JPanel {
    ImageIcon image = null;
    /** Creates new form BeanForm 
     *@params locallImage a string do local da imagem. Exemplo /com/google/api/images/image.gif   
     *Ele procura dentro dos resources ou seja a imagem pode estar num jar.
     */
    public DuduPanelImage(String localImage) {       
        setImage(localImage);
        try {
            jbInit();
        } catch (Exception e) {
            // TODO
            e.printStackTrace();
        }
    }
    public DuduPanelImage(){
        try {
            jbInit();
        } catch (Exception e) {
            // TODO
            e.printStackTrace();
        }
    }
    
    /**
     *@params locallImage a string do local da imagem. Exemplo /com/google/api/images/image.gif   
     *Ele procura dentro dos resources ou seja a imagem pode estar num jar.
     */
    public void setImage(String localImage){
        //Obtain the current classloader
        if (localImage != null && localImage.equals("") == false ){
            ClassLoader classLoader = this.getClass().getClassLoader();
            //Load the company logo image
            setImagem(new ImageIcon( classLoader.getResource(localImage) ));
        } 
    }
    
    public void setImagem(ImageIcon image){
        this.image = image;
        repaint();
    }
    public void paint(Graphics g){
      super.paint(g);
      if(this.image != null){
            g.drawImage(image.getImage() , 0, 0, this );
        }        

    }
    
    public ImageIcon  getImage(){
        return this.image;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void jbInit() throws Exception {

        setLayout(new java.awt.BorderLayout());

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
