/*
 * AbstractJPanelGeneric.java
 *
 * Created on 8 de Fevereiro de 2006, 22:02
 */

package com.dudhoo.nemesis.swing.generic;

import com.dudhoo.evilframework.swing.EvilError;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author  duduzera
 */
abstract class AbstractJPanelGeneric extends javax.swing.JPanel {
    Logger log = Logger.getLogger(this.getClass());
    /**
     * Creates new form AbstractJPanelGeneric
     */
    public AbstractJPanelGeneric() {
        jbInit();
    }
    /**
     * Adicionar um botao no rodapé
     */
    public void addButtonAtBottom(JButton bt){
        this.jPanelBottom.add(bt);
    }
    /**Seta o grande título do panelMovimentacaoEstoque
     */
    public void setGreatTitle(String text){
        this.jLabelGreatTitle.setText(text);
    }
    
    /**Seta o label do título diretamente
     */
    public void setGreatTitleLabel(JLabel label){
        this.jLabelGreatTitle = label;
    }
    /**
     * Retorna o label do grande título
     */
    public JLabel getGreatTitleLabel(){
        return this.jLabelGreatTitle;
    }
    /**Set a JPanel Inside of a scrollPane of the container, at the center.
     */
    public void setJPanelInside(JComponent panel){
        try{
            jScrollPane.setViewportView(panel);
        }catch(Exception e){
            new EvilError(null, false, e).setVisible(true);
        }
    }
    
    /**Fecha este panelMovimentacaoEstoque e remove ele de seu pai.
     */
    public void fecharPanel(){
        if(this.getParent() != null){
            this.getParent().remove(this);
        }
        Object o = this;
        o = null;
        log.info("Removido " + this.getClass().getName());        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:jbInit
    private void jbInit() {
        jLabelGreatTitle = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jLabelGreatTitle.setFont(new java.awt.Font("Trebuchet MS", 3, 14));
        add(jLabelGreatTitle, java.awt.BorderLayout.NORTH);

        jPanelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanelBottom.setBorder(new javax.swing.border.EtchedBorder());
        add(jPanelBottom, java.awt.BorderLayout.SOUTH);

        add(jScrollPane, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:jbInit
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelGreatTitle;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
